### ISSUE TITLE
Run Ultimate to check C programs

### ISSUE THREAD

**Issue by nguyenthanhvuh** [unsat/dig#15]

**Comment by ishimwed** [comment]
I pushed the ocaml script for instrumentation. 
To run it use command:
./verify.exe <source.c> <target.c> <loc> <property>
<source.c> is the source code
<target.c> is the file to save to
<loc> is the location of the invariant. In this case I just used the suffix of vtrace method. for example. vtrace1() loc wold be 1. Note: if there is only one vtrace() method loc is 0
<property> is the invariant to verify

I noticed that Utlimate takes very long to prove properties and I wonder if we can try to disprove the opposite instead because I think it is faster to find counterexamples than proofs. For example, for a property P we can instead instrument the code to verify Not P which would be faster since Not P would have counterexamples.
